import "@/styles/globals.css";
import { TRPCReactProvider } from "@/trpc/react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import { Manrope } from "next/font/google";
import { cookies } from "next/headers";
import Footer from "./_components/Footer";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "ACT IN",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body className={`font-manrope ${manrope.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <AntdRegistry>
            <ConfigProvider
              theme={{
                token: { fontFamily: "var(--font-manrope)" },
                components: {
                  Select: {
                    optionSelectedBg: "#FFF0CE",
                    fontSize: 16,
                    colorBorder: "#F17628",
                    controlHeight: 40,
                    borderRadius: 16,
                    colorBgContainer: "#F5F5F5",
                  },
                },
              }}
            >
              <main>{children}</main>
              <Footer />
            </ConfigProvider>
          </AntdRegistry>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
