import "@/styles/globals.css";
import { TRPCReactProvider } from "@/trpc/react";
import { Manrope } from "next/font/google";
import { cookies } from "next/headers";
import Footer from "./_components/Footer";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "ACT IN",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body className={`font-manrope ${manrope.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <main>{children}</main>
          <Footer />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
